### ISSUE TITLE
Windows support?

### ISSUE THREAD

**Issue by sergeyf** [spotify/annoy#97]
The readme suggests that `pip install annoy` should work on Windows, but I get the following error:

```
c:\users\s\appdata\local\temp\pip-build-jintu9\annoy\src\annoylib.h(21) : fatal error C1083: Cannot open include file: 'unistd.h': No such file or directory
```

My googling tells me that `unistd.h` is a Linux-only file.

Is there an easy fix for this?

Thanks for the awesome package!

And in case the full error message is useful:
```
C:\Anaconda>pip install annoy
Collecting annoy
  Downloading annoy-1.5.2.tar.gz (625kB)
    100% |################################| 626kB 409kB/s
Building wheels for collected packages: annoy
  Running setup.py bdist_wheel for annoy
  Complete output from command C:\Anaconda\python.exe -c "import setuptools;__file__='c:\\users\\s\\appdata\\local\\temp\\pip-build-jintu9\\annoy\\set
up.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d c:\users\s\appdata\local\temp\tmpwwwitjpip-wheel-:

  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-2.7
  creating build\lib.win-amd64-2.7\annoy
  copying annoy\__init__.py -> build\lib.win-amd64-2.7\annoy
  running build_ext
  building 'annoy.annoylib' extension
  creating build\temp.win-amd64-2.7
  creating build\temp.win-amd64-2.7\Release
  creating build\temp.win-amd64-2.7\Release\src
  C:\Program Files (x86)\Common Files\Microsoft\Visual C++ for Python\9.0\VC\Bin\amd64\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -IC:\Anaconda\inclu
de -IC:\Anaconda\PC /Tpsrc/annoymodule.cc /Fobuild\temp.win-amd64-2.7\Release\src/annoymodule.obj -O3 -march=native -ffast-math
  cl : Command line warning D9002 : ignoring unknown option '-O3'
  cl : Command line warning D9002 : ignoring unknown option '-march=native'
  cl : Command line warning D9002 : ignoring unknown option '-ffast-math'
  annoymodule.cc
  C:\Program Files (x86)\Common Files\Microsoft\Visual C++ for Python\9.0\VC\Include\xlocale(342) : warning C4530: C++ exception handler used, but unw
ind semantics are not enabled. Specify /EHsc
  c:\users\s\appdata\local\temp\pip-build-jintu9\annoy\src\annoylib.h(21) : fatal error C1083: Cannot open include file: 'unistd.h': No such file or d
irectory
  error: command 'C:\\Program Files (x86)\\Common Files\\Microsoft\\Visual C++ for Python\\9.0\\VC\\Bin\\amd64\\cl.exe' failed with exit status 2

  ----------------------------------------
  Failed building wheel for annoy
Failed to build annoy
Installing collected packages: annoy
  Running setup.py install for annoy
    Complete output from command C:\Anaconda\python.exe -c "import setuptools, tokenize;__file__='c:\\users\\s\\appdata\\local\\temp\\pip-build-jintu9
\\annoy\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record c:\users\
s\appdata\local\temp\pip-5cyqoc-record\install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    running build_ext
    building 'annoy.annoylib' extension
    C:\Program Files (x86)\Common Files\Microsoft\Visual C++ for Python\9.0\VC\Bin\amd64\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -IC:\Anaconda\inc
lude -IC:\Anaconda\PC /Tpsrc/annoymodule.cc /Fobuild\temp.win-amd64-2.7\Release\src/annoymodule.obj -O3 -march=native -ffast-math
    cl : Command line warning D9002 : ignoring unknown option '-O3'
    cl : Command line warning D9002 : ignoring unknown option '-march=native'
    cl : Command line warning D9002 : ignoring unknown option '-ffast-math'
    annoymodule.cc
    C:\Program Files (x86)\Common Files\Microsoft\Visual C++ for Python\9.0\VC\Include\xlocale(342) : warning C4530: C++ exception handler used, but u
nwind semantics are not enabled. Specify /EHsc
    c:\users\s\appdata\local\temp\pip-build-jintu9\annoy\src\annoylib.h(21) : fatal error C1083: Cannot open include file: 'unistd.h': No such file or
 directory
    error: command 'C:\\Program Files (x86)\\Common Files\\Microsoft\\Visual C++ for Python\\9.0\\VC\\Bin\\amd64\\cl.exe' failed with exit status 2

    ----------------------------------------
Command "C:\Anaconda\python.exe -c "import setuptools, tokenize;__file__='c:\\users\\s\\appdata\\local\\temp\\pip-build-jintu9\\annoy\\setup.py';exec(
compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record c:\users\s\appdata\local\temp\pip
-5cyqoc-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in c:\users\s\appdata\local\temp\pip-build-j
intu9\annoy
```

**Comment by sergeyf** [comment]
I tried another approach - clone the repo, and build with:

`python setup.py build --compiler=mingw32`
`python setup.py install`

This compiled and installed without errors, but an import call causes:

```
import annoy
Traceback (most recent call last):

  File "<ipython-input-2-149d623b088a>", line 1, in <module>
    import annoy

  File "build\bdist.win-amd64\egg\annoy\__init__.py", line 15, in <module>

  File "build\bdist.win-amd64\egg\annoy\annoylib.py", line 7, in <module>

  File "build\bdist.win-amd64\egg\annoy\annoylib.py", line 6, in __bootstrap__

ImportError: DLL load failed: A dynamic link library (DLL) initialization routine failed.
```

**Comment by erikbern** [comment]
It seems like `lseek` is defined in `unistd.h`.

See if you can do something like this and make it compile: http://stackoverflow.com/questions/341817/is-there-a-replacement-for-unistd-h-for-windows-visual-c

Annoy has been successfully used on Windows but support was added by @thirdwing and I don't know what environment was used.

**Comment by sergeyf** [comment]
It's throwing other errors about stdint.h not being found. It looks like "Visual C++ for Python" is just no good. I wonder why the MINGW version compiles but has that DLL load failure. 

Oh well, Windows is just trouble!

**Comment by thirdwing** [comment]
Yes, MinGW is used to support Windows.

I used to compile and load it. I think I need to write a Wiki page for Windows.

Give me some time.

**Comment by sergeyf** [comment]
So `python setup.py build --compiler=mingw32` should work? It seems to crap out here for some reason...

Thanks for your help!

**Comment by Turkeynator** [comment]
Hi, I tried to use *python setup.py build --compiler=mingw32* the compilation was terminated with the following message:

*In file included from src/annoymodule.cc:15:0:
src/annoylib.h:28:18: fatal error: mman.h: No such file or directory
 #include "mman.h"
                  ^
compilation terminated.
error: command 'C:\\MinGW\\bin\\gcc.exe' failed with exit status 1*

Have you written the wiki page yet on how to compile annoy for windows, or do you know a way to solve this error?
I'm relatively new to coding, so any help would be greatly appreciated!

Thank you

**Comment by erikbern** [comment]
mman.h is available in the same directory so i'm not sure what's going on here :(

**Comment by erikbern** [comment]
I realized mman.h wasn't added to the manifest – fixed now

**Comment by sergeyf** [comment]
Just as a warning to future searchers, it's still not working for me as of the latest commits. 


After running `python setup.py build --compiler=mingw32`, here is the error (skipping a slew of warnings):
```
C:\Users\S\Documents\GitHub\annoy [master]> python setup.py build --compiler=mingw32
running build
running build_py
running build_ext
building 'annoy.annoylib' extension
C:\TDM-GCC-64\bin\gcc.exe -DMS_WIN64 -mdll -O -Wall -ID:\Anaconda2\include -ID:\Anaconda2\PC -c src/annoymodule.cc -o build\temp.win-amd64-2.7\Release\src\annoymodule.o -O3 -march=native -ffast-math
writing build\temp.win-amd64-2.7\Release\src\annoylib.def
C:\TDM-GCC-64\bin\g++.exe -DMS_WIN64 -shared -s build\temp.win-amd64-2.7\Release\src\annoymodule.o build\temp.win-amd64-2.7\Release\src\annoylib.def -LD:\Anaconda2\libs -LD:\Anaconda2\PCbuild\amd64 -lpython27 -lmsvcr90 -o build\lib.win-amd64-2.7\annoy\annoylib.pyd
build\temp.win-amd64-2.7\Release\src\annoymodule.o:annoymodule.cc:(.text+0x76): undefined reference to `__imp__Py_TrueStruct'
build\temp.win-amd64-2.7\Release\src\annoymodule.o:annoymodule.cc:(.text+0x86): undefined reference to `__imp__Py_NoneStruct'
build\temp.win-amd64-2.7\Release\src\annoymodule.o:annoymodule.cc:(.text+0xb6): undefined reference to `__imp__Py_NoneStruct'
build\temp.win-amd64-2.7\Release\src\annoymodule.o:annoymodule.cc:(.text+0xee): undefined reference to `__imp__Py_NoneStruct'
build\temp.win-amd64-2.7\Release\src\annoymodule.o:annoymodule.cc:(.text+0x11a): undefined reference to `__imp__Py_TrueStruct'
build\temp.win-amd64-2.7\Release\src\annoymodule.o:annoymodule.cc:(.text+0x163): undefined reference to `__imp__Py_NoneStruct'
build\temp.win-amd64-2.7\Release\src\annoymodule.o:annoymodule.cc:(.text+0x1ce): undefined reference to `__imp__Py_NoneStruct'
build\temp.win-amd64-2.7\Release\src\annoymodule.o:annoymodule.cc:(.text+0x1f1): undefined reference to `__imp__Py_TrueStruct'
build\temp.win-amd64-2.7\Release\src\annoymodule.o:annoymodule.cc:(.text+0x235): undefined reference to `__imp__Py_NoneStruct'
build\temp.win-amd64-2.7\Release\src\annoymodule.o:annoymodule.cc:(.text+0x4de): undefined reference to `__imp__Py_NoneStruct'
build\temp.win-amd64-2.7\Release\src\annoymodule.o:annoymodule.cc:(.text+0x506): undefined reference to `__imp__Py_TrueStruct'
build\temp.win-amd64-2.7\Release\src\annoymodule.o:annoymodule.cc:(.text+0x517): undefined reference to `__imp_PyExc_IOError'
build\temp.win-amd64-2.7\Release\src\annoymodule.o:annoymodule.cc:(.text+0x55e): undefined reference to `__imp__Py_NoneStruct'
build\temp.win-amd64-2.7\Release\src\annoymodule.o:annoymodule.cc:(.text+0x586): undefined reference to `__imp__Py_TrueStruct'
build\temp.win-amd64-2.7\Release\src\annoymodule.o:annoymodule.cc:(.text+0x597): undefined reference to `__imp_PyExc_IOError'
build\temp.win-amd64-2.7\Release\src\annoymodule.o:annoymodule.cc:(.text+0xb13): undefined reference to `__imp__Py_NoneStruct'
build\temp.win-amd64-2.7\Release\src\annoymodule.o:annoymodule.cc:(.text+0xbc3): undefined reference to `__imp__Py_NoneStruct'
build\temp.win-amd64-2.7\Release\src\annoymodule.o:annoymodule.cc:(.text+0xe91): undefined reference to `__imp__Py_NoneStruct'
build\temp.win-amd64-2.7\Release\src\annoymodule.o:annoymodule.cc:(.text+0xf6c): undefined reference to `__imp__Py_NoneStruct'
build\temp.win-amd64-2.7\Release\src\annoymodule.o:annoymodule.cc:(.text+0xfa7): undefined reference to `__imp__Py_NoneStruct'
collect2.exe: error: ld returned 1 exit status
error: command 'C:\\TDM-GCC-64\\bin\\g++.exe' failed with exit status 1
```

**Comment by erikbern** [comment]
maybe try this? http://www.lfd.uci.edu/~gohlke/pythonlibs/#libpython

**Comment by erikbern** [comment]
also seems like this can be fixed: http://www.gamedev.net/topic/167094-undefined-reference-to-_imp___py_nonestruct/

do you want to try and if it works send a pull request?

**Comment by sergeyf** [comment]
Thanks @erikbern I tried the `libpython` install and it worked! Can you explain what problem that package solves?

Would you like me to uninstall `libpythin` to try the solution in your second link?

**Comment by sergeyf** [comment]
Oh this is weird - it imported fine the first time, but after reopening Python, I get this error:

```
In [1]: import annoy
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-149d623b088a> in <module>()
----> 1 import annoy

C:\Users\S\Documents\GitHub\annoy\annoy\__init__.py in <module>()
     13 # the License.
     14
---> 15 from .annoylib import *
     16
     17 class AnnoyIndex(Annoy):

ImportError: DLL load failed: A dynamic link library (DLL) initialization routine failed.
```

Grr. Let me try your second solution.

**Comment by erikbern** [comment]
weird. i just googled your error and found someone mentioning libpython :)

sure great if you want to try the other option. i don't have access to any windows machines

**Comment by sergeyf** [comment]
I've replaced all sorts of things using the construction modeled at https://docs.python.org/2/faq/windows.html#id7

So, `Py_None` is replaced by `Py_BuildValue("")` 

But what do I replace `PyExc_IOError` by? I don't do a ton of coding so this is all done by pure pattern matching =)

**Comment by erikbern** [comment]
not sure

http://stackoverflow.com/questions/31524867/compile-c-to-python-using-swig maybe?

**Comment by sergeyf** [comment]
For posterity: I updated my TDM-GCC-64 as it turns out there was a bug:

"An updated 64-bit GDB package has been released, as the Python distribution bundled with the first package was mistakenly the 32-bit version instead of the 64-bit version."

and things compile now, but `import annoy` yields 
```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-149d623b088a> in <module>()
----> 1 import annoy

C:\Users\S\Documents\GitHub\annoy\annoy\__init__.py in <module>()
     13 # the License.
     14
---> 15 from .annoylib import *
     16
     17 class AnnoyIndex(Annoy):

ImportError: No module named annoylib
```

Here is the full trace from the compilation:

```
C:\Users\S\Documents\GitHub\annoy [master]> python setup.py build --compiler=mingw32
running build
running build_py
creating build
creating build\lib.win-amd64-2.7
creating build\lib.win-amd64-2.7\annoy
copying annoy\__init__.py -> build\lib.win-amd64-2.7\annoy
running build_ext
building 'annoy.annoylib' extension
creating build\temp.win-amd64-2.7
creating build\temp.win-amd64-2.7\Release
creating build\temp.win-amd64-2.7\Release\src
C:\TDM-GCC-64\bin\gcc.exe -DMS_WIN64 -mdll -O -Wall -ID:\Anaconda2\include -ID:\Anaconda2\PC -c src/annoymodule.cc -o build\temp.win-amd64-2.7\Release
\src\annoymodule.o -O3 -march=native -ffast-math
In file included from src/annoylib.h:30:0,
                 from src/annoymodule.cc:15:
src/mman.h: In function 'void* mmap(void*, size_t, int, int, int, off_t)':
src/mman.h:102:48: warning: right shift count >= width of type [-Wshift-count-overflow]
                     (DWORD)0 : (DWORD)((off >> 32) & 0xFFFFFFFFL);
                                                ^
src/mman.h:111:52: warning: right shift count >= width of type [-Wshift-count-overflow]
                     (DWORD)0 : (DWORD)((maxSize >> 32) & 0xFFFFFFFFL);
                                                    ^
In file included from D:\Anaconda2\include/Python.h:80:0,
                 from src/annoymodule.cc:17:
src/annoymodule.cc: In function 'PyObject* py_an_load(py_annoy*, PyObject*)':
D:\Anaconda2\include/object.h:769:22: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
     ((PyObject*)(op))->ob_refcnt++)
                      ^
D:\Anaconda2\include/boolobject.h:27:31: note: in expansion of macro 'Py_INCREF'
 #define Py_RETURN_TRUE return Py_INCREF(Py_True), Py_True
                               ^
src/annoymodule.cc:109:3: note: in expansion of macro 'Py_RETURN_TRUE'
   Py_RETURN_TRUE;
   ^
src/annoymodule.cc: In function 'PyObject* py_an_save(py_annoy*, PyObject*)':
D:\Anaconda2\include/object.h:769:22: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
     ((PyObject*)(op))->ob_refcnt++)
                      ^
D:\Anaconda2\include/boolobject.h:27:31: note: in expansion of macro 'Py_INCREF'
 #define Py_RETURN_TRUE return Py_INCREF(Py_True), Py_True
                               ^
src/annoymodule.cc:128:3: note: in expansion of macro 'Py_RETURN_TRUE'
   Py_RETURN_TRUE;
   ^
src/annoymodule.cc: In function 'PyObject* py_an_build(py_annoy*, PyObject*)':
D:\Anaconda2\include/object.h:769:22: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
     ((PyObject*)(op))->ob_refcnt++)
                      ^
D:\Anaconda2\include/boolobject.h:27:31: note: in expansion of macro 'Py_INCREF'
 #define Py_RETURN_TRUE return Py_INCREF(Py_True), Py_True
                               ^
src/annoymodule.cc:240:3: note: in expansion of macro 'Py_RETURN_TRUE'
   Py_RETURN_TRUE;
   ^
src/annoymodule.cc: In function 'PyObject* py_an_unload(py_annoy*, PyObject*)':
D:\Anaconda2\include/object.h:769:22: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
     ((PyObject*)(op))->ob_refcnt++)
                      ^
D:\Anaconda2\include/boolobject.h:27:31: note: in expansion of macro 'Py_INCREF'
 #define Py_RETURN_TRUE return Py_INCREF(Py_True), Py_True
                               ^
src/annoymodule.cc:251:3: note: in expansion of macro 'Py_RETURN_TRUE'
   Py_RETURN_TRUE;
   ^
src/annoymodule.cc: In function 'PyObject* py_an_verbose(py_annoy*, PyObject*)':
D:\Anaconda2\include/object.h:769:22: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
     ((PyObject*)(op))->ob_refcnt++)
                      ^
D:\Anaconda2\include/boolobject.h:27:31: note: in expansion of macro 'Py_INCREF'
 #define Py_RETURN_TRUE return Py_INCREF(Py_True), Py_True
                               ^
src/annoymodule.cc:295:3: note: in expansion of macro 'Py_RETURN_TRUE'
   Py_RETURN_TRUE;
   ^
src/annoymodule.cc: In function 'PyObject* create_module()':
D:\Anaconda2\include/object.h:769:22: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
     ((PyObject*)(op))->ob_refcnt++)
                      ^
src/annoymodule.cc:389:3: note: in expansion of macro 'Py_INCREF'
   Py_INCREF(&PyAnnoyType);
   ^
In file included from src/annoymodule.cc:15:0:
src/annoylib.h: In instantiation of 'void AnnoyIndex<S, T, Distance, Random>::build(int) [with S = int; T = float; Distance = Euclidean; Random = Kiss
64Random]':
src/annoymodule.cc:401:3:   required from here
src/annoylib.h:46:36: warning: unknown conversion type character 'z' in format [-Wformat=]
   #define showUpdate(...) { fprintf(stderr, __VA_ARGS__ ); }
                                    ^
src/annoylib.h:292:21: note: in expansion of macro 'showUpdate'
       if (_verbose) showUpdate("pass %zd...\n", _roots.size());
                     ^
src/annoylib.h:46:36: warning: too many arguments for format [-Wformat-extra-args]
   #define showUpdate(...) { fprintf(stderr, __VA_ARGS__ ); }
                                    ^
src/annoylib.h:292:21: note: in expansion of macro 'showUpdate'
       if (_verbose) showUpdate("pass %zd...\n", _roots.size());
                     ^
src/annoylib.h: In instantiation of 'bool AnnoyIndex<S, T, Distance, Random>::load(const char*) [with S = int; T = float; Distance = Euclidean; Random
 = Kiss64Random]':
src/annoymodule.cc:401:3:   required from here
src/annoylib.h:46:36: warning: format '%lu' expects argument of type 'long unsigned int', but argument 3 has type 'std::vector<int, std::allocator<int
> >::size_type {aka long long unsigned int}' [-Wformat=]
   #define showUpdate(...) { fprintf(stderr, __VA_ARGS__ ); }
                                    ^
src/annoylib.h:374:19: note: in expansion of macro 'showUpdate'
     if (_verbose) showUpdate("found %lu roots with degree %d\n", _roots.size(), m);
                   ^
src/annoylib.h: In instantiation of 'void AnnoyIndex<S, T, Distance, Random>::build(int) [with S = int; T = float; Distance = Angular; Random = Kiss64
Random]':
src/annoymodule.cc:401:3:   required from here
src/annoylib.h:46:36: warning: unknown conversion type character 'z' in format [-Wformat=]
   #define showUpdate(...) { fprintf(stderr, __VA_ARGS__ ); }
                                    ^
src/annoylib.h:292:21: note: in expansion of macro 'showUpdate'
       if (_verbose) showUpdate("pass %zd...\n", _roots.size());
                     ^
src/annoylib.h:46:36: warning: too many arguments for format [-Wformat-extra-args]
   #define showUpdate(...) { fprintf(stderr, __VA_ARGS__ ); }
                                    ^
src/annoylib.h:292:21: note: in expansion of macro 'showUpdate'
       if (_verbose) showUpdate("pass %zd...\n", _roots.size());
                     ^
src/annoylib.h: In instantiation of 'bool AnnoyIndex<S, T, Distance, Random>::load(const char*) [with S = int; T = float; Distance = Angular; Random =
 Kiss64Random]':
src/annoymodule.cc:401:3:   required from here
src/annoylib.h:46:36: warning: format '%lu' expects argument of type 'long unsigned int', but argument 3 has type 'std::vector<int, std::allocator<int
> >::size_type {aka long long unsigned int}' [-Wformat=]
   #define showUpdate(...) { fprintf(stderr, __VA_ARGS__ ); }
                                    ^
src/annoylib.h:374:19: note: in expansion of macro 'showUpdate'
     if (_verbose) showUpdate("found %lu roots with degree %d\n", _roots.size(), m);
                   ^
src/annoylib.h: In instantiation of 'S AnnoyIndex<S, T, Distance, Random>::_make_tree(const std::vector<_Tp>&) [with S = int; T = float; Distance = Eu
clidean; Random = Kiss64Random]':
src/annoylib.h:298:34:   required from 'void AnnoyIndex<S, T, Distance, Random>::build(int) [with S = int; T = float; Distance = Euclidean; Random = K
iss64Random]'
src/annoymodule.cc:401:3:   required from here
src/annoylib.h:46:36: warning: format '%lu' expects argument of type 'long unsigned int', but argument 3 has type 'std::vector<int, std::allocator<int
> >::size_type {aka long long unsigned int}' [-Wformat=]
   #define showUpdate(...) { fprintf(stderr, __VA_ARGS__ ); }
                                    ^
src/annoylib.h:482:9: note: in expansion of macro 'showUpdate'
         showUpdate("Failed splitting %lu items\n", indices.size());
         ^
src/annoylib.h: In instantiation of 'S AnnoyIndex<S, T, Distance, Random>::_make_tree(const std::vector<_Tp>&) [with S = int; T = float; Distance = An
gular; Random = Kiss64Random]':
src/annoylib.h:298:34:   required from 'void AnnoyIndex<S, T, Distance, Random>::build(int) [with S = int; T = float; Distance = Angular; Random = Kis
s64Random]'
src/annoymodule.cc:401:3:   required from here
src/annoylib.h:46:36: warning: format '%lu' expects argument of type 'long unsigned int', but argument 3 has type 'std::vector<int, std::allocator<int
> >::size_type {aka long long unsigned int}' [-Wformat=]
   #define showUpdate(...) { fprintf(stderr, __VA_ARGS__ ); }
                                    ^
src/annoylib.h:482:9: note: in expansion of macro 'showUpdate'
         showUpdate("Failed splitting %lu items\n", indices.size());
         ^
writing build\temp.win-amd64-2.7\Release\src\annoylib.def
C:\TDM-GCC-64\bin\g++.exe -DMS_WIN64 -shared -s build\temp.win-amd64-2.7\Release\src\annoymodule.o build\temp.win-amd64-2.7\Release\src\annoylib.def -
LD:\Anaconda2\libs -LD:\Anaconda2\PCbuild\amd64 -lpython27 -lmsvcr90 -o build\lib.win-amd64-2.7\annoy\annoylib.pyd
```

**Comment by erikbern** [comment]
At this point it's probably only a problem with the path. Make sure annoylib.dll (or whatever it's called, on os x it's .so usually) is in the same directory as __init__.py

**Comment by sergeyf** [comment]
There is no .dll file anywhere in the github directory nor inside the egg when I unzip it. Probably why Python can't find it.

**Comment by erikbern** [comment]
what about the .pyd file it's building on the last file? that's probably the one you need

python setup.py doesn't put the artifacts in the right directory for some reason

**Comment by erikbern** [comment]
or just run python setup.py install!

**Comment by sergeyf** [comment]
Ok so, here is what I'm doing:

(1) Get rid of all traces of `annoy`.
(2) Clone a fresh copy.
(3) I figured out how to use pip for this: `pip install --global-option build_ext --global-option --compiler=mingw32 annoy`

So now `import annoy` causes the same error, which is weird because the .pyd file is definitely in there:

```
C:\Users\S\Documents\GitHub\annoy [master]> pip uninstall annoy
Uninstalling annoy-1.6.2:
  d:\anaconda2\lib\site-packages\annoy-1.6.2-py2.7.egg-info
  d:\anaconda2\lib\site-packages\annoy\__init__.py
  d:\anaconda2\lib\site-packages\annoy\__init__.pyc
  d:\anaconda2\lib\site-packages\annoy\annoylib.pyd
```

So I just don't know what the deal is!

**Comment by erikbern** [comment]
I'm sorry, no idea what's going on. Maybe someone else with Windows can help?

**Comment by sergeyf** [comment]
No problem - thanks for your effort. I will keep subscribed to this thread and hope against hope.

**Comment by sergeyf** [comment]
Fixed with the latest commit!

**Comment by erikbern** [comment]
nice!

**Comment by cmpute** [comment]
still meet the problem, missing `unistd.h`.
Try both installing from pip and source code, the problem remains
when trying building from source using mingw, an error occured
![image](https://user-images.githubusercontent.com/9154441/27836289-a296c448-6093-11e7-88e4-b83cb75b2d32.png)

**Comment by erikbern** [comment]
think this is unrelated to annoy

https://stackoverflow.com/questions/24683305/python-cant-install-packages-typeerror-unorderable-types-nonetype-str
http://bugs.python.org/issue2698
